MODEL:
  name: "MAESTER"
  img_size: 80
  patch_size: 5
  embed: 192
  embed_dim: 192
  depth: 14
  num_heads: 1
  decoder_embed_dim: 128
  decoder_depth: 7
  decoder_num_heads: 8
  mlp_ratio: 2.0
  mask_ratio: 0.5
  pos_encode_w: 0.08
  central_patch: 4
DATASET:
  name: "Cem500K"
  path_list:
    #- "../dataset/high_c1_source_tensor"
    #- "../dataset/high_c2_source_tensor"
    #- "../dataset/high_c3_source_tensor"
    - "/home/codee/scratch/dataset/small_set/tensor1.tiff"
    #- "/home/codee/scratch/dataset/small_set/tensor2.tiff"
    #- "/home/codee/scratch/dataset/small_set/tensor3.tiff"
  pad: 4 #ex. from [2, 2, 2] image to [18,18,18] image
  aug: "betaaug2D"
  # depend on number of GPUs
  num_workers: 4
  batch_size: 128 #32
  vol_size: 80
  patch_size: 5 # 240 / 24 = 10 # 240 / 8 = 30
ENGINE:
  name: "train_engine"
  epoch: 1000 #2800
OPTIM:
  name: "adamw"
  lr: 1.5e-3
  reg_w: 1.0e-5
